name: Generate Snake Animation

permissions:
  contents: write  # Memberi akses push ke GitHub Actions

on:
  schedule:
    - cron: "0 0 * * *"  # Jalan setiap hari jam 00:00 UTC
  workflow_dispatch:       # Bisa dijalankan manual dari tab Actions

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ilhamhabibilah
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push the generated SVG to output branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

          git clone --branch=output https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} output-branch
          cp dist/github-contribution-grid-snake.svg output-branch/

          cd output-branch
          git add github-contribution-grid-snake.svg
          git commit -m "update snake animation" || echo "No changes to commit"
          git push
