name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Setiap hari jam 00:00 UTC
  workflow_dispatch:      # Bisa dijalankan manual

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ilhamhabibilah
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages (output branch)
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ github.token }}
