name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Setiap hari jam 00:00 UTC
  workflow_dispatch:      # Bisa dijalankan manual

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ilhamhabibilah
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push the generated SVG to output branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
          git clone --branch=output https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} output-branch
          cp dist/github-contribution-grid-snake.svg output-branch/
          
          cd output-branch
          git add github-contribution-grid-snake.svg
          git commit -m "update snake animation"
          git push
