name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Menjalankan setiap hari jam 00:00 UTC
  workflow_dispatch:      # Bisa dijalankan manual dari tab Actions

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ilhamhabibilah
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push the snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
